### PR TITLE
Fix requests to github api

### LINKED ISSUE #44: The number of repos that we have starred is wrong
The number of repos that the user has starred shows up as 100, if the number is more than 100 because of the `per_page=100`in the GET request URL

image

### PR DESCRIPTION
**Pull request by Green-Ranger11**
### Why This PR Adds Value

This PR gets the users actual starred repos as well as actual number of followers since our previous requests were using a per_page query hence if the maximum values that would be returned would only be depending on the max value we used on the per_page query.

### What This PR Adds

- Correct number of followers
- Correct number of starred repos
- Gets user data
- Removes unnecessary axios request as octokit can actually authorize with a access token
- Minor refactor

### Screenshot

dash
Again RIP my stats :(

#### Hacky Method
- The way we get the number of starred repos is a big hacky as I'm using a third party library (trust me I tried to find a way where we could do this without it but it requires way too much work and there are a lot of edge cases). Essentially in every header where you make a request to the `/user/starred` endpoint the response comes with a header called link in which there is a `ref_last` field which indicates the last page. If you make a request with the `per_page` set to 1 the `re_last` literally equates to the total count since the request you makes only returns one starred repo per request.
#### Don't need the other data returned in the response.
- Adding on to the previous point, since we are using Restful api we get back tons of data on the starred repo when essentially we only need the link header. As our application scales this might actually slow it down. There are multiple ways which we could alleviate a possible perfomance hit such as caching but I think the best way would actually be using the graphQL api instead since we literally don't need the body only one field in the header. This also applies to the repo information we are getting which we use to get the total stars.
#### File and possible DRY in future development
- The github.ts file is already getting pretty big and would like to have some helper or service methods to just help take the load off. In addition, all our api requests are being done in a single file but we might have to make these same requests in another api route hence we would literally be repeating ourselves. Having a service or extension of some sort in which we could just use across different routes would be helpful.

### Issue This PR Closes

This closes #44

### CODE REVIEW

File: gitdash/pages/api/github.ts [hunk 1]
```diff
@@ -26,51 +23,41 @@ export default async function GetDetails(
...
-  const starredCount = reposStarred.data.length;
+  // Get Number of starred repos by using a weird hack since Github api doesnt have a endpoint.
+  // You parse the link header in the response to get the rel_last which relates to the totat
+  // count if the per_page is set to one
+
+  // Making the request to get the response :/
+  const reposStarred = await octokit.request("GET /user/starred?per_page=1");
+
+  // Parsing the starred repos using a library
+  const parse = require("parse-link-header");
```
Comment (anandrajaram21) [inline gitdash/pages/api/github.ts]: Please move this line to the top of the file to keep all imports on top, and use the `import Stuff from Stuff` syntax instead of require to keep everything consistent

File: gitdash/package.json [hunk 2]
```diff
@@ -19,6 +19,7 @@
     "framer-motion": "^4.1.17",
     "next": "11.0.1",
     "next-auth": "^3.27.3",
+    "parse-link-header": "^1.0.1",
```
Comment (anandrajaram21) [inline gitdash/package.json:21]: Can you tell me more about this parse-link-header package?

**Review by anandrajaram21 — CHANGES_REQUESTED** [review]

File: gitdash/package.json (hunk 2 above)
Comment (Green-Ranger11) [reply gitdash/package.json:21]: So basically there's no clear way to get the total number of starred repos. The way is you get it is what I mentioned in the PR description. Is making a simple request to that `starred` endpoint and in the headers you will get a field called `link`.
That header contains the true number of starred repos.

What that library does is it parses that header so you can get the actual total value which is `last_page` property as shown below:
`const starredCount = parsed.last.page;`	

Basically from the header you get this
`https://api.github.com/user/9287/repos?page=1&per_page=1; rel=head, https://api.github.com/user/9287/repos?page=88&per_page=1; rel=last`

What we need is this:
`page=88` which is the `rel=last` field which contains the actual total count.

That library parses the header to something like this (Going off my memory you can console.log if you wish):
`{ head:
   { page: '1',
     per_page: '1',
     rel: 'next',
     url: 'https://api.github.com/user/9287/repos?page=1&per_page=1' 
	},
  last:
   { page: '88',
     per_page: '1',
     rel: 'last',
     url: 'https://api.github.com/user/9287/repos?page=88&per_page=1' 
	} 
}`

In essence it's simply a parser and at first I spent like 2 hours looking for a simpler way we could parse and did find some suggestions but it was too much to implement because there are a lot of edge cases because the example is not the only type of header you can get. You can get no header if there are no starred repos and you can also get a header with an extra field. What that library does is handle all the edge-cases that we might miss. I also detest it because it doesn't have a typescript version. Maybe we can write our own parser when we find ourselves with some time.

I really don't like this solution as it's a bit hacky but the github api does have its limitations.

Comment (anandrajaram21) [reply gitdash/package.json:21]: Ah, so the number of pages is the number of starred repos? ngl, that's a pretty smart solution

**Review by prakharrathi25 — APPROVED** [review]

**Review by anandrajaram21 — APPROVED** [review]
Good one @Green-Ranger11. Now you just have to fix the merge conflicts
